Repository microsoft/winget-create, pull requests merged in 2021-06, with the labels that each got.

#56 Clean up temp files from installer download
  NOTICE.txt
  pipelines/azure-pipelines.yml
  src/WingetCreateCore/Common/PackageParser.cs
Labels: Issue-Bug

#59 Removing redundant internetClient capability
  src/WingetCreatePackage/Package.appxmanifest
Labels: Issue-Docs

#58 Modifying logging to only call string.Format if there are format arguments
  src/WingetCreateCLI/Logger/Logger.cs
Labels: Issue-Bug

#55 Add check for handling updating multiple distinct installer url manifests
  src/WingetCreateCLI/Commands/UpdateCommand.cs
  src/WingetCreateCLI/Properties/Resources.Designer.cs
  src/WingetCreateCLI/Properties/Resources.resx
  src/WingetCreateCore/Common/PackageParser.cs
  src/WingetCreateTests/WingetCreateTests/Resources/TestPublisher.MultipleInstallerApp.yaml
  src/WingetCreateTests/WingetCreateTests/Resources/TestPublisher.TestApp.yaml
  src/WingetCreateTests/WingetCreateTests/TestConstants.cs
  src/WingetCreateTests/WingetCreateTests/TestUtils.cs
  src/WingetCreateTests/WingetCreateTests/UnitTests/GitHubTests.cs
  src/WingetCreateTests/WingetCreateTests/UnitTests/NewCommandTests.cs
  src/WingetCreateTests/WingetCreateTests/UnitTests/UpdateCommandTests.cs
  src/WingetCreateTests/WingetCreateTests/WingetCreateTests.csproj
Labels: Issue-Bug

#63 Adding schema link headers to serialized manifests
  src/WingetCreateCLI/Commands/BaseCommand.cs
  src/WingetCreateCLI/Program.cs
  src/WingetCreateCore/Common/GitHub.cs
  src/WingetCreateCore/Common/Serialization.cs
  src/WingetCreateTests/WingetCreateTests/UnitTests/CharacterValidationTests.cs
  src/WingetCreateTests/WingetCreateTests/UnitTests/GitHubTests.cs
Labels: Issue-Feature

#54 Add duplicate id check for existing package identifiers
  src/WingetCreateCLI/Commands/NewCommand.cs
  src/WingetCreateCLI/Commands/UpdateCommand.cs
  src/WingetCreateCLI/Program.cs
  src/WingetCreateCLI/Properties/Resources.Designer.cs
  src/WingetCreateCLI/Properties/Resources.resx
  src/WingetCreateCore/Common/GitHub.cs
  src/WingetCreateTests/WingetCreateTests/UnitTests/GitHubTests.cs
Labels: Issue-Bug, Issue-Feature

#67 Modifying Update command to update ProductCode for MSIs
  doc/update.md
  src/WingetCreateCLI/Program.cs
  src/WingetCreateCore/Common/PackageParser.cs
Labels: Issue-Feature

#73 Adding parsing logic for Burn installerType
  src/WingetCreateCore/Common/PackageParser.cs
Labels: Issue-Bug

#79 Adding a self-contained standalone exe to our release for users without .NET installed
  README.md
  pipelines/azure-pipelines.release.yml
Labels: Issue-Feature

#91 Removing BOM prefix from manifest content
  src/WingetCreateCLI/Commands/NewCommand.cs
  src/WingetCreateCLI/Commands/UpdateCommand.cs
  src/WingetCreateCore/Common/Serialization.cs
Labels: Issue-Bug

#94 Add Telemetry Opt-Out and Settings Command
  README.md
  doc/settings.md
  src/WingetCreateCLI/Commands/SettingsCommand.cs
  src/WingetCreateCLI/Models/SettingsModel.cs
  src/WingetCreateCLI/Program.cs
  src/WingetCreateCLI/Properties/Resources.Designer.cs
  src/WingetCreateCLI/Properties/Resources.resx
  src/WingetCreateCLI/Schemas/settings.schema.0.1.json
  src/WingetCreateCLI/Telemetry/TelemetryEventListener.cs
  src/WingetCreateCLI/Telemetry/TelemetryManager.cs
  src/WingetCreateCLI/UserSettings.cs
  src/WingetCreateCLI/WingetCreateCLI.csproj
  src/WingetCreateTests/WingetCreateTests/UnitTests/SettingsCommandTests.cs
  src/WingetCreateTests/WingetCreateTests/WingetCreateTests.csproj
Labels: Issue-Feature
